name: Gradle Test

on:
  pull_request:
    branches: [ main, develop, vivi108-patch-1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Docker Compose
        run: docker-compose -f docker-compose.yml up --build --abort-on-container-exit
      # - name: Gradle 빌드 캐싱
      #   id: gradle-cache
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.gradle/caches
      #       ~/.gradle/wrapper
      #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      #     restore-keys: |
      #       ${{ runner.os }}-gradle-
      # - name: Gradle 테스트
      #   run: ./gradlew test
